name: Generate ASCII Artwork
on: push
jobs:
    # ascii_job:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout repo.
    #           uses: actions/checkout@v4
            
    #         # - name: Install Cowsay Program
    #         #   run: sudo apt-get install cowsay -y

    #         # - name: Execute Cowsay CMD
    #         #   run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWR" >> dragon.txt
            
    #         # - name: Test file exists
    #         #   run: grep -i "dragon" dragon.txt
            
    #         # - name: Read File
    #         #   run: cat dragon.txt

    #         - name: Checkout Repo Files
    #           run: ls -ltra

    #         - name: Executing shell script.
    #           run: |
    #                chmod +x ascii-script.sh
    #                ./ascii-script.sh

    build_job_1:
      runs-on: ubuntu-latest
      steps:
        - name: Install cowsay program
          run: sudo apt-get install cowsay -y
        
        - name: Execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a dragon ... WFTTT" >> dragon.txt

        # - name: Sleep for 30 seconds
        #   run: sleep 30
        
        - name: Upload Dragon text File
          uses: actions/upload-artifact@v4
          with:
              name: dragon-text-file
              path: dragon.txt
        
      
    test_job_2:
      runs-on: ubuntu-latest
      needs: build_job_1
      steps:
        # - name: Sleep for 10 seconds
        #   run: sleep 10
        
        - name: Download Dragon text File
          uses: actions/download-artifact@v4
          with:
              name: dragon-text-file

        - name: Test if file exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job_3:
      runs-on: ubuntu-latest
      needs: test_job_2
      steps:

        - name: Download Dragon text File
          uses: actions/download-artifact@v4
          with:
              name: dragon-text-file

        - name: Read File
          run: cat dragon.txt
        
        - name: Deploy
          run: echo Deploying ....
